
---
# The name of your assignment
name: simple-assignment
# Should a check failure "break" the Gradle run?
break: true
# Should a check failure immediately "break" the Gradle run?
fastfail: false
# What level of indentation does the body of this file use?
indent: 2
# What version of GatorGrader should this assignment use?
version: v1.1.0
---

# A check inside these blocks runs on the "." directory against the "build.gradle" file
config:
gatorgrader.yml:
    --description "Make a gatorgrader.yml file" ConfirmFileExists

# A check without a surrounding block runs in the "." directory
--description "Have at least 7 commits" CountCommits --count 7

# A pure check runs directly as a shell command
(pure) test 2 -eq 2
